#
# DOCKER_IP=192.168.X.X docker-compose up
#
version: '3'

services:
  hublin:
    build: .
    container_name: hublin
    image: linagora/hublin:latest
    links:
    - mongo:mongo
    - redis:redis
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - MONGO_HOST=mongo
    - MONGO_PORT=27017
    - MONGO_DBNAME=hublin
    ports:
    - "8080:8080"
  mongo:
    container_name: hublin_mongo
    image: mongo:3.2
    ports:
      - "27017:27017"
  redis:
    container_name: hublin_redis
    image: redis:latest
    ports:
      - "6379:6379"

